dist: trusty
sudo: required
language: c

# Always test GCC - Clang has problems with coverage report generation
compiler:
  - gcc

# edit here, Set Environment Variables
env:
  - WORKDIR=$TRAVIS_BUILD_DIR
  - COIN_SRC="https://github.com/bulwark-crypto/Bulwark.git"
  - COIN_NAME=$(basename "${COIN_SRC%.*}")

  
# Install dependencies
before_install:
  - echo "$COIN_NAME"
  - echo "$WORKDIR"
  - cd "$WORKDIR"
  - chmod +x ./build-wallet.sh
  
install: true

# Compile dependencies and Wallet
script: ./build-wallet.sh
