dist: trusty
sudo: required
language: c

# Always test GCC - Clang has problems with coverage report generation
compiler:
  - gcc

# edit here, Set Environment Variables
env:
  - WORKDIR=$TRAVIS_BUILD_DIR
  - COIN_SRC="https://github.com/bulwark-crypto/Bulwark.git"
  - COIN_NAME=$(basename ${COIN_SRC%.*})
  
# Install dependencies
before_install:
  - chmod +x ./build-deps.sh
  - chmod +x ./build-wallet.sh
  - sudo ./build-deps.sh
  
  
# Compile dependencies and Wallet
install: sudo ./build-wallet.sh

deploy:
  skip_cleanup: true

# Upload artifacts to amazon S3, detail https://docs.travis-ci.com/user/uploading-artifacts/
addons:
  artifacts:
    s3_region: "ap-southeast-1"
    working_dir: $WORKDIR/$COIN_NAME/release