sudo: required
language: c

# Always test GCC - Clang has problems with coverage report generation
compiler:
  - gcc

# edit here, Set Environment Variables
env:
  global:
    - WORKDIR=$TRAVIS_BUILD_DIR COIN_SRC="https://github.com/bulwark-crypto/Bulwark.git" COIN_NAME="Bulwark"

  
# Install dependencies
before_install:
  - chmod +x ./build-wallet.sh

install: true
  
script: travis_wait 20 ./build-wallet.sh

