dist: trusty
sudo: required
language: c

# Always test GCC - Clang has problems with coverage report generation
compiler:
  - gcc

# edit here, Set Environment Variables
env:
  - WORKDIR=$TRAVIS_BUILD_DIR
  - COIN_SRC="https://github.com/bulwark-crypto/Bulwark.git"
  - COIN_NAME=$(basename ${COIN_SRC%.*})
  
# Install dependencies
before_install:
  - sudo apt-get update -qq -y
  - sudo apt-get install p7zip-full autoconf automake autopoint bash bison bzip2 cmake flex gettext git g++ gperf intltool libffi-dev libtool libltdl-dev libssl-dev libxml-parser-perl make openssl patch perl pkg-config python ruby scons sed unzip wget xz-utils
  - sudo apt-get install g++-multilib libc6-dev-i386
  
  
# Compile dependencies and Wallet
script:
  - $WORKDIR/build-deps.sh
  - $WORKDIR/build-wallet.sh

# Upload artifacts to amazon S3, detail https://docs.travis-ci.com/user/uploading-artifacts/
addons:
  artifacts:
    s3_region: "ap-southeast-1"
    working_dir: $WORKDIR/$COIN_NAME/release