language: c

# Always test GCC - Clang has problems with coverage report generation
compiler:
  - gcc

# edit here, Set Environment Variables
env:
  global:
    - WORKDIR=$TRAVIS_BUILD_DIR COIN_SRC="https://github.com/bulwark-crypto/Bulwark.git" COIN_NAME="Bulwark"

  
# Install dependencies
before_install:
  - echo "$COIN_NAME"
  - echo "$WORKDIR"
  - chmod +x ./build-wallet.sh
  - sh ./build-wallet.sh
  
install: ./build-wallet.sh

